uploads = []
outputs = []

[[generated]]
id = "PM9DyYTRgGUIo7023-1V2"
uri = "file://artifacts/get-mumm/public/koshari.png"
type = "image"
title = "Egyptian Koshari dish"

[[generated]]
id = "lvKH3bn0T_PQBLal1SjCX"
uri = "file://artifacts/get-mumm/public/molokhia.png"
type = "image"
title = "Egyptian Molokhia soup"

[[generated]]
id = "RhkDyjxpn2U0sDPVzNn5-"
uri = "file://artifacts/get-mumm/public/fatta.png"
type = "image"
title = "Egyptian Fatta with meat"

[[generated]]
id = "G8JDtyAw1TKwI5QKy8nar"
uri = "file://artifacts/get-mumm/public/mahshi.png"
type = "image"
title = "Egyptian Mahshi stuffed vegetables"

[[generated]]
id = "BvgOrnHVpLXQ66jHbZn7y"
uri = "file://artifacts/get-mumm/public/kofta.png"
type = "image"
title = "Egyptian Kofta skewers"

[[generated]]
id = "wOrHMzafVSFjq3SerWTr1"
uri = "file://artifacts/get-mumm/public/umm_ali.png"
type = "image"
title = "Egyptian Umm Ali dessert"

[[generated]]
id = "BbFBYwUimJSQTFOGTviml"
uri = "file://artifacts/get-mumm/public/chef1.png"
type = "image"
title = "Portrait of female Egyptian chef"

[[generated]]
id = "_buTvIIEc5RAXoDJGMlEE"
uri = "file://artifacts/get-mumm/public/chef2.png"
type = "image"
title = "Portrait of young female chef"

[[generated]]
id = "pcTuIQUG0TwTuYy4ox0ju"
uri = "file://artifacts/get-mumm/public/family_dining.png"
type = "image"
title = "Family dining together"

[[generated]]
id = "x0G7VCX24T2eVXApEpBu0"
uri = "file://artifacts/get-mumm/public/office_catering.png"
type = "image"
title = "Office team eating catering"
